server:
  port: 8081
  servlet:
    context-path: /api
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog-demo
    username: root
    password: 1234
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
  session:
    timeout: 86400
    store-type: redis
# springdoc-openapi项目配置
springdoc:
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.lucky.blogdemo.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn
